services:
  - docker
  
before_install:
  - docker image build -t ntopng_img:ntopng_bionic_lts -f ubu18/Dockerfile .
  - docker volume create ntopng_data
  - docker run -v ntopng_data:/data --net=host -t -p 3000:3000 -i ntopng_img:ntopng_bionic_lts
  
script:
  - curl -vvv http://localhost:3000
